# Generated by Django 3.1.7 on 2021-03-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blurb', models.TextField()),
                ('host_comments', models.TextField()),
                ('start_date', models.DateField()),
                ('url', models.TextField(unique=True)),
                ('episode_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster_url', models.TextField()),
                ('release_date', models.DateField()),
                ('media_type', models.CharField(max_length=50)),
                ('external_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MMSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_image_url', models.CharField(max_length=200)),
                ('user_type', models.IntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', related_query_name='recommendation', to='mmsapi.media')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediareviews', related_query_name='mediareview', to='mmsapi.media')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewusers', related_query_name='reviewuser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='Toplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplistusers', related_query_name='toplistuser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watched', models.DateField()),
                ('rating', models.IntegerField()),
                ('prating', models.IntegerField()),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediawatcheds', related_query_name='mediawatched', to='mmsapi.media')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchedusers', related_query_name='watcheduser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='ToWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediatowatchs', related_query_name='mediatowatch', to='mmsapi.media')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towatchusers', related_query_name='towatchuser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='TopListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('toplist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplistitems', related_query_name='toplistitem', to='mmsapi.toplist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplistitemusers', related_query_name='toplistitemuser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='TopListComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('toplist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplistcomments', related_query_name='toplistcomment', to='mmsapi.toplist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplistcommentusers', related_query_name='toplistcommentuser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewcomments', related_query_name='reviewcomment', to='mmsapi.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewcommentusers', related_query_name='reviewcommentuser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendationvotes', related_query_name='recommendationvote', to='mmsapi.recommendation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendationvoteusers', related_query_name='recommendationvoteuser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediarankings', related_query_name='mediaranking', to='mmsapi.media')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankingusers', related_query_name='rankinguser', to='mmsapi.mmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='HostRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episoderecommendations', related_query_name='episoderecommendation', to='mmsapi.episode')),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendationmedia', related_query_name='recommendationmedia', to='mmsapi.media')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodecomments', related_query_name='episodecomment', to='mmsapi.episode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodecommentusers', related_query_name='episodecommentuser', to='mmsapi.mmsuser')),
            ],
        ),
    ]
