# Generated by Django 3.1.7 on 2021-03-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
