# Generated by Django 3.1.7 on 2021-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='mmsuser',
            name='bio',
            field=models.TextField(),
        ),
    ]
