# Generated by Django 3.1.7 on 2021-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapi', '0002_auto_20210307_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
