# Generated by Django 3.1.7 on 2021-03-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapi', '0003_episode_episode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
