# Generated by Django 3.1.7 on 2021-03-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapi', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towatch',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
