# Generated by Django 3.1.7 on 2021-03-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapi', '0004_auto_20210316_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watched',
            name='date_watched',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='watched',
            name='prating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watched',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
