# Generated by Django 3.1.7 on 2021-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapi', '0005_auto_20210317_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watched',
            name='date_watched',
            field=models.DateField(auto_now_add=True),
        ),
    ]
