# Generated by Django 3.1.7 on 2021-03-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapi', '0006_auto_20210317_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
